version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "Sunil0916"
    reviewers:
      - "srkambham"
    commit-message:
      prefix: "pip"
